name: Flutter Lint

on:
  push:
    branches: [ "master", "development" ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.8
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run Dart analyzer
        run: flutter analyze